version: '3.8'

services:
  app:
    build: .	# 用根目錄的 Dockerfile 建 image
    container_name: taskmanager-app
    ports:
      - "8080:8080"		# 映射容器的 8080 到本機
    depends_on:
      - redis
      - rabbitmq
    environment:		# Spring Boot 連線 Redis 和 RabbitMQ
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: "6379"
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: "5672"

  redis:
    image: redis:7-alpine
    container_name: taskmanager-redis
    ports:
      - "6379:6379"
   # volumes:        先註解，不將資料持久化
    #  - redis-data:/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: taskmanager-rabbitmq
    ports:
      - "5672:5672"    # RabbitMQ 傳遞消息的 port
      - "15672:15672"  # 管理介面
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
   # volumes:        先註解，不將資料持久化
    #  - rabbitmq-data:/var/lib/rabbitmq

# volumes:        先註解，不將資料持久化
#  redis-data:
#  rabbitmq-data: